[package]
name = "backend"
version = "0.1.0"
edition = "2024"
exclude = ["config/*"]

[dependencies]
axum = "0.6.20"
indexmap = "2.9.0"
mysql = "26.0.0"
serde_json = "1.0.140"
tokio = { version = "1.0", features = ["full"] }


